name: Lint the source code
on:
  [pull_request, push]
jobs:
  test:
    name: Lint the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install packages
        run: npm install
      - name: Lint with eslint
        run: npm run lint
